services:
  frontend:
    image: timmijinks/bitch-frontend:latest
    container_name: BITCH-frontend
    ports:
      - 3000:3000
    restart: always

  backend:
    image: timmijinks/bitch-backend:latest
    container_name: BITCH-backend
    ports:
      - 8000:8000
    links:
      - mongo
    restart: always

  mongo:
    image: mongo:latest
    hostname: "mongo"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    command: mongod --auth
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    restart: always

  watchtower:
    image: containerrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - frontend
      - backend
      - mongo
      - nginx
    restart: always
